# Generated by Django 2.1.5 on 2019-01-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=60000)),
                ('time', models.CharField(max_length=30)),
                ('typeId', models.IntegerField()),
                ('typeIdName', models.CharField(max_length=30)),
                ('readNum', models.IntegerField(default=0, null=True)),
                ('commentNum', models.IntegerField(default=0, null=True)),
                ('isPublish', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('typeId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=10, null=True)),
                ('path', models.CharField(max_length=100)),
                ('orderNumber', models.CharField(max_length=10)),
                ('isEnable', models.IntegerField()),
                ('parentId', models.IntegerField()),
                ('allPower', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=20)),
                ('userTypeId', models.IntegerField()),
                ('menuId', models.IntegerField()),
                ('power', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeId', models.IntegerField()),
                ('typeIdName', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=3000)),
                ('time', models.CharField(max_length=30)),
                ('essayId', models.IntegerField()),
                ('isCheck', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
